# Generated by Django 3.2.6 on 2021-08-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('description_short', models.TextField(blank=True)),
                ('description_long', models.TextField(blank=True, null=True)),
                ('coordinates', models.JSONField()),
            ],
        ),
    ]
