# Generated by Django 3.2.6 on 2021-08-26 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placesimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placesimages',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_places', to='places.places'),
        ),
    ]
