# Generated by Django 3.2.6 on 2021-08-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_placesimages_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='placesimages',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='placesimages',
            name='imgs',
            field=models.ImageField(upload_to='', verbose_name='Картинка'),
        ),
    ]
