# Generated by Django 3.2.6 on 2021-08-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20210826_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='places',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AlterModelOptions(
            name='placesimages',
            options={'ordering': ('position',), 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterField(
            model_name='placesimages',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, default=1, null=True, verbose_name='Позиция'),
        ),
    ]
