# Generated by Django 3.2.6 on 2021-09-09 05:15

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20210827_1102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlacesImages',
            new_name='PlaceImage',
        ),
        migrations.RenameModel(
            old_name='Places',
            new_name='Place',
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_places', to='places.place'),
        ),
    ]
