# Generated by Django 3.2.6 on 2021-09-09 05:21

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20210909_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='coordinates',
            field=models.JSONField(verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Интересные места'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_places', to='places.place', verbose_name='Места'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Позиция'),
        ),
    ]
