# Generated by Django 3.2.6 on 2021-09-09 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20210909_0521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='placeimage',
            old_name='imgs',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_short',
            new_name='short_description',
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Интересные места'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_places', to='places.place', verbose_name='Места'),
        ),
    ]
